blog/urls.py
from django.urls import path

from .views import (
    BlogListView, BlogDetailView, UpdateCreateView, BlogCreateView, BlogUpdateView, BlogDeleteView,
)

urlpatterns = [
    path('update/new/', UpdateCreateView.as_view(), name='update_new'),
    path('post/<int:pk>/delete/',
         BlogDeleteView.as_view(), name='post_delete'),
    path('post/<int:pk>/edit/',
         BlogUpdateView.as_view(), name='post_edit'),
    path('post/new/', BlogCreateView.as_view(), name='post_new'),
    path('post/<int:pk>/', BlogDetailView.as_view(), name='post_detail'),
    path('', BlogListView.as_view(), name='home'),
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('blog.urls')),
]

if settings.DEBUG:  # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse


# Create your models here.


class Post(models.Model):
    REQUIREMENT_TYPES = (
        ('N', "New Requirement"),
        ('E', "Enhancement"),
        ('R', "Roll Out"),
        ('T', "Training"),
    )
    PRIORITASS = (
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
    )
    TARGETS = (
        ('1', 'TW-I'),
        ('2', 'TW-II'),
        ('3', 'TW-III'),
        ('4', 'TW-IV'),
    )
    DIR_APS = (
        ('CON', 'Controller'),
        ('DEV', 'Development'),
        ('FIN', 'Finance & Treasury'),
        ('HR', 'HR-GA'),
        ('ICT', 'ICT & DM'),
        ('AUDIT', 'Internal Audit'),
        ('LEGAL', 'Legal'),
        ('NUN', 'Nunukan'),
        ('ONWJ', "ONWJ"),
        ('OPS', 'Operation & Production'),
        ('PHI', 'PHI'),
        ('PPRM', 'PPRM'),
        ('QHSSE', 'QHSSE'),
        ('REL', 'Relation'),
        ('SCM', 'SCM'),
        ('SK', 'Siak-Kampar'),
        ('CO', 'Commercial'),
        ('WMO', 'WMO'),
    )
    user1 = models.CharField(max_length=15)
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE, related_name='posts')
    dir_ap = models.CharField(max_length=5, choices=DIR_APS)
    requirement = models.TextField()
    requirement_type = models.CharField(max_length=1, choices=REQUIREMENT_TYPES)
    prioritas = models.CharField(max_length=1, choices=PRIORITASS)
    target = models.CharField(max_length=1, choices=TARGETS)
    budget = models.IntegerField()
    last_updated = models.DateTimeField(auto_now_add=True)
    document = models.FileField(upload_to='documents/')

    def __str__(self):
        return self.requirement[:50]

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])


class Update(models.Model):
    STATUSS = (
        ('C', 'Closed'),
        ('D', 'Dropped'),
        ('E', 'Execution'),
        ('I', 'Initiation'),
        ('P', 'Planning'),
    )
    posting = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='updates',)
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE, related_name='updates',)
    last_update = models.DateField(auto_now=True)
    progress = models.IntegerField()
    status = models.CharField(max_length=1, choices=STATUSS)
    status_akhir = models.TextField()

    def __str__(self):
        return self.status_akhir[:50]


    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.posting.id)])

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

# Create your views here.
from .models import Post, Update


class BlogListView(ListView):
    model = Post
    template_name = 'home.html'
    context_object_name = 'all_posts_list'


class BlogDetailView(DetailView):
    model = Post
    template_name = 'post_detail.html'


class UpdateListView(ListView):
    model = Update
    template_name = 'update.html'
    context_object_name = 'all_updates_list'


class BlogCreateView(CreateView):
    model = Post
    template_name = 'post_new.html'
    fields = ['requirement', 'user1', 'author', 'dir_ap', 'requirement_type', 'prioritas', 'target', 'budget',
              'document']


class UpdateCreateView(CreateView):
    model = Update
    template_name = 'update_new.html'
    fields = ['posting', 'author', 'progress', 'status', 'status_akhir']


class BlogUpdateView(UpdateView):
    model = Post
    template_name = 'post_edit.html'
    fields = ['requirement', 'user1', 'author', 'dir_ap', 'requirement_type', 'prioritas', 'target', 'budget',
              'document']


class BlogDeleteView(DeleteView):
    model = Post
    template_name = 'post_delete.html'
    success_url = reverse_lazy('home')

templates/base.html
<!DOCTYPE html>

<html lang="en">
{% load static %}
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>BD Monitoring</title>
  </head>
<body>

<nav class="navbar navbar-dark bg-primary navbar-expand-sm">
          <a class="navbar-brand" href="{% url 'home' %}">
            <img src="https://s3.eu-central-1.amazonaws.com/bootstrapbaymisc/blog/24_days_bootstrap/logo_white.png"
                 width="30" height="30" alt="logo">
            BD Monitoring
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-list-4"
                  aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

        <div class="collapse navbar-collapse" id="navbar-list-4">
            {% if user.is_authenticated %}
            <a class="navbar-nav ml-auto" style="color:white"> Helo
                {{ user.username }}
                <ul class="navbar-nav">
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <img src="https://s3.eu-central-1.amazonaws.com/bootstrapbaymisc/blog/24_days_bootstrap/fox.jpg"
                           width="40" height="40" class="rounded-circle">
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                       <a class="dropdown-item" href="{% url 'logout' %}">Log Out</a>
                    </div>
                  </li>
                </ul>
            </a>

            {% else %}
                <form class="form-inline ml-auto">
                    <a href="{% url 'login' %}" class="btn btn-danger">Log In</a>
                </form>
            {% endif %}
        </div>
    </nav>
        <div class="container">
            {% block content %}
            {% endblock content %}
        </div>
<!-- Optional JavaScript : jQuery first, then Popper.js, then Bootstrap JS-->

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>


{% block js %}

{% endblock js %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
{% if user.is_authenticated %}

<p></p>
<a class="btn btn-primary" role="button" href="{% url 'post_new' %}">New Req</a>
<p></p>
<table  id="table_id"   class="table table-hover">
        <thead class="thead-dark">
          <tr>
            <th>Requirement</th>
            <th>User Name</th>
            <th>Director/AP</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
            {% for post in all_posts_list %}
                <tr>
                    <td scope="row">
                        <a href="{% url 'post_detail' post.pk %}">{{  post.requirement }}</a>
                    </td>
                    <td>
                        {{ post.user1   }}
                    </td>
                    <td>
                        {{ post.get_dir_ap_display }}
                    </td>
                    <td>
                        {{ post.updates.last.get_status_display }}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
</table>

{% else %}
<a>Selamat datang di BD Monitoring</a>
<p>Silahkan login!</p>
{% endif %}

{% endblock content %}
 {% block js %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
     <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.10.18/af-2.3.0/b-1.5.2/b-colvis-1.5.2/b-flash-1.5.2/b-html5-1.5.2/b-print-1.5.2/cr-1.5.0/fh-3.1.4/r-2.2.2/datatables.min.css"/>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.10.18/af-2.3.0/b-1.5.2/b-colvis-1.5.2/b-flash-1.5.2/b-html5-1.5.2/b-print-1.5.2/cr-1.5.0/fh-3.1.4/r-2.2.2/datatables.min.js"></script>
<script>
    $(document).ready( function () {
    $('#table_id').DataTable({
    dom: 'B<"clear">lfrtip',
    buttons: {
        name: 'primary',
        buttons: [ 'copy', 'csv', 'excel', 'pdf' ]
        }}
    );
} );
</script>
</div>
{% endblock %}

templates/post_delete.html
{% extends 'base.html' %}

{% block content %}
        <h1>Delete Req:</h1>
        <form action="" method="post">{% csrf_token %}
            <p>Betulkan mau delete "{{ object.requirement }}"?</p>
            <input type="submit" value="Confirm" />
        </form>

{% endblock content %}

templates/post_detail.html
{% extends 'base.html' %}

{% block content %}
<table class="table table-stripped">
    <tbody>
       <tr>
           <td><h2>Requirement</h2></td><td><h2><a href=""> {{  object.requirement }}  </a></h2></td>
       </tr>
       <tr>
           <td>User name</td><td>  {{ object.user1   }}</td>
       </tr>
       <tr>
           <td>Author</td><td>{{ object.author   }}</td>
       </tr>
       <tr>
           <td>Director/AP</td><td>{{ object.get_dir_ap_display }}</td>
       </tr>
       <tr>
           <td>Req. Type</td><td>{{ object.get_requirement_type_display   }}</td>
       </tr>
       <tr>
           <td>Prioritas</td><td>{{ object.get_prioritas_display   }}</td>
       </tr>
       <tr>
           <td>Target</td><td>{{ object.get_target_display   }}</td>
       </tr>
       <tr>
           <td>Budget</td><td>{{ object.budget   }} KIDR</td>
       </tr>
       <tr>
           <td>Last Updated</td><td>{{ object.last_updated}}</td>
       </tr>
       <tr>
           <td>Document</td><td><a href="{{ object.document.url }}"> {{ object.document.url }}</a> </td>
       </tr>
       <tr>
           <td><a class="btn btn-primary" href="{% url 'post_edit' post.pk %}" role="button">Edit Req</a></td>
           <td><a class="btn btn-danger" href="{% url 'post_delete' post.pk %}" role="button">Delete Req</a></td>
       </tr>

    </tbody>
</table>


<h2><a href="">Status: </a></h2>
<table class="table table-hover">

    <thead class="thead-dark">
          <tr>
            <th>Oleh</th>
            <th>tanggal</th>
            <th>Progres</th>
            <th>Status</th>
            <th>Status Akhir</th>
          </tr>
    </thead>
    <tbody>

            {% for comment in post.updates.all %}
            <tr>
                <td>{{ comment.author }}</td>
                <td>{{ comment.last_update }} </td>
                <td>{{ comment.progress }} % </td>
                <td>{{ comment.get_status_display }}</td>
                <td>{{ comment.status_akhir }}</td>
            </tr>
            {% endfor %}
    </tbody>
</table>

<a class="btn btn-primary" href="{% url 'update_new' %}" role="button">New Status</a>


{% endblock content %}

templates/post_edit.html
{% extends 'base.html' %}

{% block content %}
    <h1>Requirement edit:</h1>
    <form action ="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update" />
    </form>
{% endblock content %}

templates/post_new.html
{% extends 'base.html' %}

{% block content %}
    <h1>Requirement baru:</h1>
    <form action ="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save" />
    </form>
{% endblock content %}

templates/update_new.html
{% extends 'base.html' %}

{% block content %}
    <h1>Update status:</h1>
    <form action ="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save" />
    </form>
{% endblock content %}